### ISSUE TITLE
exceptions.SSLError

### ISSUE THREAD

**Issue by SzuWeiChen** [stu01509/TaiwanLotteryCrawler#56]
### 問題 Issue

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.taiwanlottery.com.tw', port=443): 
Max retries exceeded with url: /Lotto/Dailycash/history.aspx 
(Caused by SSLError(
    SSLCertVerificationError(1, 
        '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

### 重現步驟 Reproduce

重現該行為的步驟(Steps to reproduce the behavior):
1. 執行 '....'
2. See error
3. ...

### 環境 Environment

- Python Version:
- Operating System:
- TaiwanLotteryCrawler Version:

### 截圖 Screenshot

**Comment by stu01509** [comment]
Hi, 感謝您的回報, 目前已經修正一版 https://github.com/stu01509/TaiwanLotteryCrawler/pull/57 待驗證完畢後會再 Release 一版到 PyPI
